RESULT			= Pokemochi
SOURCES			= save.ml pokemon.ml main.ml
LIBS			= bigarray sdl sdlttf sdlmixer sdlloader str unix
INCDIRS			= +sdl
PACKS			= extlib sdl.sdlimage sdl.sdlmixer sdl.sdlttf sdl
THREADS 		= true
OCAMLLDFLAGS	= -cclib "-framework Cocoa"

include OCamlMakefile
