# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apantiez <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/18 11:18:52 by apantiez          #+#    #+#              #
#    Updated: 2015/06/25 17:44:53 by apantiez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT    = atom
SOURCES    = ./atom.ml \
			 ./carbon.ml \
			 ./hydrogen.ml \
			 ./oxygen.ml \
			 ./uranium.ml \
			 ./nitrogen.ml \
			 main.ml
LIBS    =
include OCamlMakefile
