# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apantiez <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/18 11:18:52 by apantiez          #+#    #+#              #
#    Updated: 2015/06/25 18:10:48 by apantiez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT    = Alkanes
SOURCES    = ./atom.ml \
			 ./carbon.ml \
			 ./hydrogen.ml \
			 ./oxygen.ml \
			 ./uranium.ml \
			 ./nitrogen.ml \
			 ./molecule.ml \
			 ./water.ml \
			 ./carbondioxyde.ml \
			 ./tnt.ml \
			 ./butan.ml \
			 ./benzylparaben.ml \
			 ./trans_cinnamic_acid.ml \
			 ./alkane.ml \
			 ./methane.ml \
			 ./ethane.ml \
			 ./octane.ml \
			 main.ml
LIBS    =
include OCamlMakefile


