# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: apantiez <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/06/18 11:18:52 by apantiez          #+#    #+#              #
#    Updated: 2015/06/24 18:36:52 by apantiez         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

RESULT    = Army
SOURCES    = people.ml \
			 dalek.ml \
			 doctor.ml \
			 army.ml \
			 galifrey.ml \
			 main.ml
LIBS    =
include OCamlMakefile
